### ISSUE TITLE
反向代理模式下报错

### ISSUE THREAD

**Issue by godfyun** [loveinsky100/panama#9]
经常会出现这个错误
client <----------------  proxy closed
io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.3.1:53
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:267)
        at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:466)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
java.lang.NullPointerException
        at org.leo.server.panama.client.AbstractClient.send(AbstractClient.java:54)
        at org.leo.server.panama.vpn.proxy.AbstractShadowSocksProxy.sendRequest2Target(AbstractShadowSocksProxy.java:95)
        at org.leo.server.panama.vpn.proxy.impl.ShadowSocksProxy.doProxy(ShadowSocksProxy.java:58)
        at org.leo.server.panama.vpn.reverse.server.ReverseShadowSocksServer.doProxy(ReverseShadowSocksServer.java:152)
        at org.leo.server.panama.vpn.reverse.server.ReverseShadowSocksServer.lambda$doRequest$3(ReverseShadowSocksServer.jav
a:113)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at org.leo.server.panama.vpn.reverse.server.ReverseShadowSocksServer.doRequest(ReverseShadowSocksServer.java:113)
        at org.leo.server.panama.vpn.reverse.core.ReverseCoreClient.doCompleteResponse(ReverseCoreClient.java:70)
        at org.leo.server.panama.vpn.reverse.core.ReverseCoreClient.doCompleteResponse(ReverseCoreClient.java:24)
        at org.leo.server.panama.client.handler.TCPClientHandler.channelReadComplete(TCPClientHandler.java:59)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:398)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:380)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelReadComplete(AbstractChannelHandlerContext.java:373)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelReadComplete(DefaultChannelPipeline.java:1439)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:398)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:380)
        at io.netty.channel.DefaultChannelPipeline.fireChannelReadComplete(DefaultChannelPipeline.java:971)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:168)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:648)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)

是连接超时么？

**Comment by loveinsky100** [comment]
抱歉，现在才看到，之前实在是比较忙。反向代理我自己用的比较少，我这边复现看下。

**Comment by loveinsky100** [comment]
看了下逻辑没什么问题，能确认下你的部署环境吗，目前看起来是内网服务返回数据给外网服务超时。
